In [10]:
s = '12345'
ln = len(s)
def get_move_iter(s):
    i = 0
    while True:
        yield s[i]
        i = i+1 if i<len(s)-1 else 0

In [11]:
i = 0
for j in get_move_iter('12345'):
    print(j)
    i += 1
    if i>25:
        break


1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1
2
3
4
5
1


In [8]:
import numpy as np
HORZ = np.array([1,1,1,1],)
PLUS = np.array([[0,1,0], [1,1,1], [0,1,0]])
ELL = np.array([[0,0,0], [0,0,1], [0,0,0]])
VERT = np.array([[1], [1], [1], [1]])
BOX = np.array([[1,1], [1,1]])

h, = HORZ.shape

In [14]:
chamber = np.zeros(shape=(10,7))
print(chamber)
np.roll(PLUS,2)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


array([[1, 0, 0],
       [1, 0, 1],
       [1, 1, 0]])

In [37]:
PLUS.shape

(3, 3)

In [43]:
r = ['a','b','c','d']
list(reversed(r[0:-1]))

['c', 'b', 'a']

In [41]:
r[-1:-1:-1]

[]

In [36]:
chamber = np.zeros(shape=(10,7))
chamber[0:3,0:3] = PLUS
print(chamber)
chamber = np.zeros(shape=(10,7))
chamber[1:4,0:3] = PLUS
print(chamber)

[[0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [51]:
ins = '>>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>'
print(len(ins))
n = 1514285714288
n / 40

40


37857142857.2

In [58]:
q = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
n = len(q)
#p = 0
#print(q[p:n])
#p = 3
#print(q[p:n] + q[0:p])
for i in range(0,n):
    print(q[i:n] + q[0:i])

['a', 'b', 'c', 'd', 'e', 'f', 'g']
['b', 'c', 'd', 'e', 'f', 'g', 'a']
['c', 'd', 'e', 'f', 'g', 'a', 'b']
['d', 'e', 'f', 'g', 'a', 'b', 'c']
['e', 'f', 'g', 'a', 'b', 'c', 'd']
['f', 'g', 'a', 'b', 'c', 'd', 'e']
['g', 'a', 'b', 'c', 'd', 'e', 'f']


In [64]:
q = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
print(q)
q[0:6] = q[1:7]
q[6] = 'h'
print(q)

['a', 'b', 'c', 'd', 'e', 'f', 'g']
['b', 'c', 'd', 'e', 'f', 'g', 'h']
